<?php
declare(strict_types=1);

/**
 * Concatenate modular CSS into a single stylesheet (avoids @import waterfall).
 *
 * Usage: php tools/bundle-css.php
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    header('Content-Type: text/plain; charset=UTF-8');
    echo "CLI only.\n";
    exit(1);
}

$cssRoot = dirname(__DIR__) . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR . 'css';
$manifest = [
    'base/fonts.css',
    'base/tokens.css',
    'base/reset.css',
    'base/typography.css',
    'base/utilities.css',
    'layout/container.css',
    'layout/section.css',
    'layout/header.css',
    'layout/footer.css',
    'components/buttons.css',
    'components/nav.css',
    'components/tabs.css',
    'components/modals.css',
    'components/scrollbar.css',
    'components/lightbox.css',
    'sections/hero.css',
    'sections/about.css',
    'sections/tracks.css',
    'sections/gallery.css',
    'sections/merch.css',
    'sections/contact.css',
    'responsive/responsive.css',
    'pages.css',
];

$out = "/* Auto-generated by tools/bundle-css.php — do not edit by hand. */\n";
foreach ($manifest as $rel) {
    $path = $cssRoot . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $rel);
    if (!is_file($path)) {
        fwrite(STDERR, "Missing: {$rel}\n");
        exit(1);
    }
    $out .= "\n/* ===== {$rel} ===== */\n";
    $out .= file_get_contents($path);
    if (!str_ends_with($out, "\n")) {
        $out .= "\n";
    }
}

$dest = $cssRoot . DIRECTORY_SEPARATOR . 'style.bundle.css';
if (file_put_contents($dest, $out) === false) {
    fwrite(STDERR, "Could not write {$dest}\n");
    exit(1);
}

echo 'Wrote ' . $dest . ' (' . number_format(strlen($out)) . " bytes)\n";
