<?php
declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    header('Content-Type: text/plain; charset=UTF-8');
    echo "CLI only.\n";
    exit(1);
}

/**
 * One-shot: Montréal slug fix, featured pool lyrics, live Wrong Exit collision slug.
 */

$root = dirname(__DIR__);
require_once $root . '/includes/helpers.php';
require_once $root . '/data/tracks.php';

$path = $root . '/data/lyrics-imported.php';
$imported = is_file($path) ? require $path : [];
$imported = is_array($imported) ? $imported : [];

$bad = 'montr-al-tourist-in-my-own-heart';
$good = 'montreal-tourist-in-my-own-heart';
if (isset($imported[$bad]) && !isset($imported[$good])) {
    $imported[$good] = $imported[$bad];
    fwrite(STDOUT, "Copied Montréal lyrics {$bad} -> {$good}\n");
} elseif (isset($imported[$good])) {
    fwrite(STDOUT, "Good Montréal key already present\n");
} else {
    fwrite(STDOUT, "Montréal source key missing — will fetch from Suno\n");
}

$jobs = [];
foreach ($featuredPool as $track) {
    $jobs[] = [
        'slug' => syzygy_slugify((string) $track['title']),
        'title' => (string) $track['title'],
        'href' => (string) $track['href'],
    ];
}

foreach (($playlists['syzygy-void-live']['tracks'] ?? []) as $track) {
    if (strcasecmp((string) $track['title'], 'Wrong Exit') === 0) {
        $jobs[] = [
            'slug' => 'wrong-exit-syzygy-void-live',
            'title' => (string) $track['title'] . ' (Live)',
            'href' => (string) $track['href'],
        ];
        break;
    }
}

if (!isset($imported[$good])) {
    foreach (($playlists['wondering-traveler']['tracks'] ?? []) as $track) {
        if (stripos((string) $track['title'], 'MONTR') !== false) {
            $jobs[] = [
                'slug' => $good,
                'title' => (string) $track['title'],
                'href' => (string) $track['href'],
            ];
            break;
        }
    }
}

$ctx = stream_context_create([
    'http' => [
        'timeout' => 25,
        'ignore_errors' => true,
        'header' => "User-Agent: Mozilla/5.0 (compatible; SYZYGY.VOID-Lyrics-Importer/1.0)\r\nAccept: application/json\r\nReferer: https://suno.com/\r\n",
    ],
]);

$failures = [];
foreach ($jobs as $job) {
    $href = $job['href'];
    if (!preg_match('~/song/([a-f0-9-]{36})~i', $href, $m)) {
        $failures[] = $job['title'] . ' (bad href)';
        continue;
    }
    $clipId = strtolower($m[1]);
    $raw = @file_get_contents('https://studio-api.prod.suno.com/api/clip/' . rawurlencode($clipId), false, $ctx);
    $clip = is_string($raw) ? json_decode($raw, true) : null;
    $prompt = is_array($clip) ? trim((string) ($clip['metadata']['prompt'] ?? '')) : '';
    $owner = is_array($clip) ? trim((string) ($clip['handle'] ?? '')) : '';

    if ($prompt === '' || $owner !== 'syzygy86') {
        if ($owner === 'syzygy86' && $prompt === '') {
            $prompt = "[Instrumental]\n\n(No lyric prompt was stored on this Suno clip.)";
        } else {
            $failures[] = $job['title'] . " (owner={$owner}, prompt=" . strlen($prompt) . ')';
            continue;
        }
    }

    $imported[$job['slug']] = [
        'status' => 'ready',
        'body' => $prompt,
        'source' => $href,
        'source_clip_id' => $clipId,
        'imported_at' => gmdate('c'),
    ];
    fwrite(STDOUT, "Imported {$job['title']} -> {$job['slug']}\n");
}

ksort($imported);

$php = "<?php\n";
$php .= "declare(strict_types=1);\n\n";
$php .= "/** Generated by tools/import-suno-lyrics.php from public SYZYGY.VOID Suno clips. */\n";
$php .= 'return ' . var_export($imported, true) . ";\n";

$tmp = $path . '.tmp';
if (file_put_contents($tmp, $php, LOCK_EX) === false || !rename($tmp, $path)) {
    fwrite(STDERR, "Could not write {$path}\n");
    exit(1);
}

if ($failures !== []) {
    fwrite(STDERR, "Failures:\n- " . implode("\n- ", $failures) . "\n");
    exit(2);
}

fwrite(STDOUT, 'Done. Total imported keys: ' . count($imported) . "\n");
