<?php
declare(strict_types=1);

/**
 * One-time/public-data importer for a release already defined in data/tracks.php.
 *
 * Usage:
 *   php tools/import-suno-lyrics.php chapel-protocol-aftermath
 */

$root = dirname(__DIR__);

require_once $root . '/includes/helpers.php';
require_once $root . '/data/tracks.php';

$releaseKey = trim((string) ($argv[1] ?? 'chapel-protocol-aftermath'));
$playlist = $playlists[$releaseKey] ?? null;

if (!is_array($playlist)) {
    fwrite(STDERR, "Unknown release key: {$releaseKey}\n");
    exit(1);
}

$outputPath = $root . '/data/lyrics-imported.php';
$existing = is_file($outputPath) ? require $outputPath : [];
$existing = is_array($existing) ? $existing : [];
$imported = $existing;
$failures = [];

$context = stream_context_create([
    'http' => [
        'timeout' => 20,
        'ignore_errors' => true,
        'header' => "User-Agent: SYZYGY.VOID-Lyrics-Importer/1.0\r\nAccept: application/json\r\n",
    ],
]);

foreach (($playlist['tracks'] ?? []) as $track) {
    $title = trim((string) ($track['title'] ?? ''));
    $songUrl = trim((string) ($track['href'] ?? ''));

    if ($title === '' || !preg_match('~/song/([a-f0-9-]{36})~i', $songUrl, $match)) {
        $failures[] = $title !== '' ? $title : 'Untitled track';
        continue;
    }

    $clipId = strtolower($match[1]);
    $apiUrl = 'https://studio-api.prod.suno.com/api/clip/' . rawurlencode($clipId);
    $raw = @file_get_contents($apiUrl, false, $context);
    $clip = is_string($raw) ? json_decode($raw, true) : null;
    $prompt = is_array($clip) ? trim((string) ($clip['metadata']['prompt'] ?? '')) : '';
    $isPublic = is_array($clip) && !empty($clip['is_public']);
    $owner = is_array($clip) ? trim((string) ($clip['handle'] ?? '')) : '';

    if ($prompt === '' || !$isPublic || $owner !== 'syzygy86') {
        $failures[] = $title;
        continue;
    }

    $slug = syzygy_slugify($title);
    $imported[$slug] = [
        'status' => 'ready',
        'body' => $prompt,
        'source' => $songUrl,
        'source_clip_id' => $clipId,
        'imported_at' => gmdate('c'),
    ];

    fwrite(STDOUT, "Imported {$title}\n");
}

ksort($imported);

$php = "<?php\n";
$php .= "declare(strict_types=1);\n\n";
$php .= "/** Generated by tools/import-suno-lyrics.php from public SYZYGY.VOID Suno clips. */\n";
$php .= 'return ' . var_export($imported, true) . ";\n";

$tempPath = $outputPath . '.tmp';
if (file_put_contents($tempPath, $php, LOCK_EX) === false || !rename($tempPath, $outputPath)) {
    fwrite(STDERR, "Could not write {$outputPath}\n");
    exit(1);
}

if ($failures !== []) {
    fwrite(STDERR, 'Not imported: ' . implode(', ', $failures) . "\n");
    exit(2);
}

fwrite(STDOUT, 'Imported ' . count($playlist['tracks'] ?? []) . " lyrics into data/lyrics-imported.php\n");
